pipeline {
    agent any
    stages {
        stage('clean & install') {
            steps {
                bat "mvn clean install -f cicdpipelineapp/pom.xml"
            }
        }
        stage('Testing'){
        	steps {
        		bat "mvn test -f cicdpipelineapp/"
        	}
        }
        stage('Packaging'){
        	steps {
        		bat "mvn package -f cicdpipelineapp/"
        	}
        }
        stage('Deploying'){
        	steps {
        		echo "Deploy begins......."
        		bat "xcopy C:/Source/" "C:/Destination/"
        	}
        }
        
    }
}
